### ISSUE TITLE
Style adjustments

### ISSUE THREAD

**Issue by danilo-cupido** [fac22/tiger-not-a-cat#20]
- Centre content for bigger screens 
- Fix footer position 
- Resize input form for bigger screens 
- Style alert box

**Comment by danilo-cupido** [comment]
- Style Submit button and Reload button (we can call them in a different way)

**Comment by jijip41** [comment]
- style input forms

**Comment by jijip41** [comment]
missed 'style alert box' - will be done by end of the day
